version: '3'

dotenv:
  - .env

tasks:
  createdb:
    - docker exec -it postgres12 createdb --username={{.DB_USER}} --owner={{.DB_USER}} simple_bank
  dropdb:
    - docker exec -it postgres12 dropdb simple_bank
  postgres:
    - docker run --name postgres12 -p 5432:5432 -e POSTGRES_USER={{.DB_USER}} -e POSTGRES_PASSWORD={{.DB_PASSWORD}} -d postgres:12-alpine
  migrateup:
    - migrate -path db/migration -database "postgresql://{{.DB_USER}}:{{.DB_PASSWORD}}@localhost:5432/simple_bank?sslmode=disable" -verbose up
  migratedown:
    - migrate -path db/migration -database "postgresql://{{.DB_USER}}:{{.DB_PASSWORD}}@localhost:5432/simple_bank?sslmode=disable" -verbose down    
  sqlc:
    - sqlc generate